### ISSUE TITLE
[Feature] 3rd Party Portal Section 

### ISSUE THREAD

**Issue by moritzkirstein** [deltaDAO/mvg-portal#52]
## Motivation / Problem
We have already demonstrators with various use-cases live and in use. These demos can and should be linked from the MVG landing page. We need to prepare a basic design to integrate 2 (or more in future) portals for now.

## Solution
- [x] prepare design on figma
- [x] implement the design

**Comment by LucaMilanese90** [comment]
@moritzkirstein are you planning to use some sort of background for the section or something to make the portals pop a little? Because otherwise the asset teaser stripped of all the other info looks maybe a little bit too simple

![Screenshot 2022-02-21 at 12 18 32](https://user-images.githubusercontent.com/20192135/154945229-3d3c32d3-24a1-4908-a9fe-809f4f5e12d8.png)

We could maybe consider a column layout for example

![Screenshot 2022-02-21 at 12 13 17](https://user-images.githubusercontent.com/20192135/154944443-8c360b5d-4295-440b-a7ca-3e6e5026009a.png)
